# Generated by Django 4.1.6 on 2023-02-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_remove_person_city_alter_person_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
